---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup.yml

    - name: Import VPC setup Variable
      include_vars: vars/vpc_setup.yml

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Sec Grp for bastion Host
      ec2_group:
        name: Bastion-host-sg        
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "vpc-06e34bfc30b919bfa"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags: 
          name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
          name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "subnet-00c51f66573e327a3"
      register: bastionHost_out
