---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup.yml

    - name: Import VPC setup Variable
      include_vars: vars/vpc_setup.yml

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Sec Grp for bastion Host
      ec2_group:
        name: Bastion-host-sg        
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "vpc-06e34bfc30b919bfa"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      community.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
      filters:
        "tag:Name": "Bastion_host"
        "tag:Project": "Vprofile"
        "tag:Owner": "Devops Team"
      register: bastionHost_out

    - name: Check if instance already exists
      set_fact:
        instance_exists: "{{ bastionHost_out.instances | length > 0 }}"

    - name: Creating new instance if it doesn't exist
      when: not instance_exists
      community.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
      tags:
        name: "Bastion_host"
        Project: Vprofile
        Owner: Devops Team
      vpc_subnet_id: "subnet-00c51f66573e327a3"
      register: new_bastionHost_out
